name: 'Standar version action'
description: 'Bump version create changelog and tag version then push back to github"'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-commit'
  color: 'purple'
inputs:
  prerelease:
    description: 'set if it\'s a prerelease or not'
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
outputs:
  version: # output will be available to future steps
    description: "The generated version to output"
